[WIP] Nested virt bool
ansibleplaybookbundle/kubevirt-apb pull request #19
Opened 2018-03-02 21:31 UTC by rthallisey

depends-on: https://github.com/openshift/ansible-service-broker/issues/812

2018-03-05 08:03 UTC, mareklibra requested changes
Nice :-)

I think we should support AMD as well.
Verification step should be improved.

2018-03-05 08:03 UTC, mareklibra commented on roles/kubevirt-apb/tasks/provision.yml
> +  shell: rmmod kvm-intel && modprobe kvm-intel || true
What about AMD?

2018-03-05 08:03 UTC, mareklibra commented on roles/kubevirt-apb/tasks/provision.yml
> +  register: result
If successful, single letter `Y` is expected to be printed out here

2018-03-05 12:59 UTC, rthallisey commented
@mareklibra This may be out of scope of an apb because it involves making changes to a host machine.  I created https://github.com/openshift/ansible-service-broker/issues/812 so there's a discussion around this started, but in the near term this probably makes more sense to do outside of an apb.  If https://github.com/openshift/ansible-service-broker/issues/812 is merged later on, we can always come back and add this.

2018-07-11 10:23 UTC, lukas-bednar commented
I was dealing with nested vt on our infra too, and [here](https://galaxy.ansible.com/lukas-bednar/ansible-role-nested-virtualization) is how I deal with that, you could use there as well if you find it handy:

2018-07-11 10:23 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2022-01-14 16:02 UTC, closed without merging